Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/opt/projects/mana/mana/settings.py", line 90, in <module>
    C2_KS_USER=admin
NameError: name 'admin' is not defined
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/opt/projects/mana/mana/settings.py", line 90, in <module>
    C2_KS_USER=admin
NameError: name 'admin' is not defined
Validating models...

0 errors found
June 16, 2014 - 19:46:49
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[16/Jun/2014 20:01:13] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
Validating models...

0 errors found
June 16, 2014 - 20:01:10
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[16/Jun/2014 20:06:57] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:06:58] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:07:27] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:07:27] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:07:28] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:07:29] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:07:29] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:07:30] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:07:42] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:07:43] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:14:01] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
[16/Jun/2014 20:44:05] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1395
Validating models...

0 errors found
June 16, 2014 - 20:06:55
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[16/Jun/2014 20:48:35] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 500 70629
Validating models...

0 errors found
June 16, 2014 - 20:48:12
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[16/Jun/2014 20:49:18] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 500 70635
Validating models...

0 errors found
June 16, 2014 - 20:49:17
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[16/Jun/2014 20:54:02] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 500 81392
[16/Jun/2014 20:56:39] "GET /api/evacuate/12_ff-a3/ HTTP/1.1" 200 1407
Validating models...

0 errors found
June 16, 2014 - 20:54:01
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/opt/projects/mana/api/views.py:28: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

[16/Jun/2014 21:20:07] "GET /api/face/ HTTP/1.1" 200 20
[16/Jun/2014 21:26:39] "GET /api/face/ HTTP/1.1" 200 20
[16/Jun/2014 21:26:40] "GET /api/face/ HTTP/1.1" 200 20
[16/Jun/2014 21:26:43] "GET /api/face/ HTTP/1.1" 200 20
Validating models...

0 errors found
June 16, 2014 - 21:19:22
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Jun/2014 14:02:35] "GET /api/evacuate/asd/ HTTP/1.1" 200 1919
[24/Jun/2014 14:03:08] "GET /api/free-res/ HTTP/1.1" 500 68617
Validating models...

0 errors found
June 24, 2014 - 14:02:30
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Jun/2014 14:10:54] "GET /api/free-res/ HTTP/1.1" 500 68519
Validating models...

0 errors found
June 24, 2014 - 14:10:53
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Jun/2014 14:15:15] "GET /api/free-res/ HTTP/1.1" 500 68730
[24/Jun/2014 14:15:16] "GET /api/free-res/ HTTP/1.1" 500 68730
Validating models...

0 errors found
June 24, 2014 - 14:15:07
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Jun/2014 14:26:33] "GET /api/free-res/ HTTP/1.1" 500 68530
[24/Jun/2014 14:26:34] "GET /api/free-res/ HTTP/1.1" 500 68530
[24/Jun/2014 14:27:20] "GET /api/free-res/ HTTP/1.1" 500 68533
[24/Jun/2014 14:27:20] "GET /api/free-res/ HTTP/1.1" 500 68530
Validating models...

0 errors found
June 24, 2014 - 14:24:58
Django version 1.6.2, using settings 'mana.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
